### ISSUE TITLE
Refactor pctl profiles global functions into providers and builders

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#115]
Right now, there are these global functions all over the place:

```go
//MakeArtifacts returns artifacts for a subscription
type MakeArtifacts func(sub profilesv1.ProfileSubscription, gitClient git.Git)([]profile.Artifact, error)
```

These functions make progress difficult as every change we would like to make to generating artifacts needs to change the function definition. Which doesn't scale really well. 

We need to create some interfaces to abstract this behaviour. And while we are there, we also need some builders abstraction on the Kind switch so we can compartmentalise those changes and make them easy to extend once we inevitably start expending them.

This should be done sooner rather than later, because with every feature it will get more difficult to do.

**Comment by Callisto13** [comment]
@Skarlso can this be closed?

**Comment by Skarlso** [comment]
Oh yes. Thanks!
