### ISSUE TITLE
Command-line help for pctl install is out-of-date

### ISSUE THREAD

**Issue by bigkevmcd** [weaveworks/pctl#118]
**What happened?**

The help message is wrong

https://github.com/weaveworks/pctl/blob/main/cmd/pctl/install.go#L19 still refers to a subscription.

**Comment by Callisto13** [comment]
i think there are many things which are out of date, so a general review would be good

**Comment by aclevername** [comment]
> https://github.com/weaveworks/pctl/blob/main/cmd/pctl/install.go#L19 still refers to a subscription.
Fixed in https://github.com/weaveworks/pctl/pull/137

The rest of the help text looks good to me :+1:
