### ISSUE TITLE
pctl requires GIT_TOKEN, flux requires GITHUB_TOKEN

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#121]
this is annoying af

**Comment by aclevername** [comment]
Its because this works for multiple git providers https://github.com/jenkins-x/go-scm
```
GitHub
GitHub Enterprise (you specify a server URL)
BitBucket Server
BitBucket Cloud
GitLab
Gitea
Gogs
Fake
```

**Comment by Callisto13** [comment]
I think we should still work to improve the UX here. If users are already setting one thing for Flux, why should they set a completely different var containing the exact same value.
