### ISSUE TITLE
Install with both `--create-pr` and `--out` fails if out is not a git repo

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#122]
The output value in this case should not be a git repo, but a target directory within the repo provided in `--pr-repo`.

```
$ pctl install \
   --profile-url https://github.com/Callisto13/demo-observability-profile \
   --profile-path observe-one \
   --create-pr \
   --pr-repo Callisto13/demo-gitops-repo \
   --out wow-such-demo/default/observe-one \
  --pr-branch install-observability
generating subscription for profile /:

Creating a PR to repo Callisto13/demo-gitops-repo with base main and branch install-observability
using driver: github and serverURL:
directory is not a git repository: stat wow-such-demo/default/observe-one/.git: no such file or directory

```

**Comment by aclevername** [comment]
@Skarlso did this get fixed when you changed the `--out` logic?

**Comment by Skarlso** [comment]
For the record, `--pr-repo` does not define a location for the repository. So it doesn't know where that repo is located.
I'm going to close this issue now because many things changed since, so if this is a problem again, please re-open it.
