### ISSUE TITLE
Sparse output when installing (generating local files)

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#124]
```sh
$ pctl install weaveworks-catalog/observe-one
generating subscription for profile weaveworks-catalog/observe-one:

# nothing. cool story bro
$
```

maybe let's have a success message or something? say where the files have been created?

**Comment by Skarlso** [comment]
># nothing. call story bro
># nothing. cool story bro
:trollface: 

I agree. Also, that output is kind of odd and maybe needs a re-write too.
