### ISSUE TITLE
Add a check that `--out` HAS to be a relative path in pctl

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#126]
Right now we work on the assumption that you are running pctl in the flux repository. You can also define an `--out` if you want to generate things into a folder. However, we don't check if that path is relative or absolute and if it is absolute it's likely not going to work because locally cloned artifacts require the path to be relative to the root of the gitrepository.

Now, this is easier said than done, because all of the tests are relying on --out being a TEMP folder, otherwise they would pollute the current running folder with generated content and step on each other while doing so.

So this requires a bit of think on how to do or maybe we just document it and that's it. Discuss.

**Comment by bigkevmcd** [comment]
I think this should really be changed to accept absolute paths, relative paths require the user to work out the correct path from their directory, absolute is better.

**Comment by Skarlso** [comment]
Work out the correct path of what? The assumption is that pctl is running in the flux repo. Otherwise, we have no way of finding out the root folder, which is required for the cloned local artifacts to work.
