### ISSUE TITLE
Use `flux create` instead of `flux bootstrap` in pctl integration test

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#127]
Flux create can be used to create a flux repo with the existing deployment key currently present on the pctl-test-repo instead of doing a `bootstrap` which always creates a new key that has to be cleaned up.

**Comment by aclevername** [comment]
The `flux bootstrap` approach also currently fails for me because I don't have admin permissions to add a deploy key to the `pctl-test-repo`, so another reason to move away from this :smile:
