### ISSUE TITLE
[Spike] Introduce pctl configuration file

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#138]
This is something of a spike/investigation, the outcome of which should be a written proposal.

---------------

The UX of `pctl install` is getting more elaborate and less user friendly. The addition of the `--git-repository` flag means users have to discover and provide information to `pctl` in a way which feels a little awkward.

One "solution" (more of a shuffle) is to have a config file, `.pctl-cfg` or whatever, which users would generate to "prepare" their repo for profiles. We would use it to store and recover various bits of configuration. The aim of this is to make it easier and less weird for users to provide pctl with information it needs to operate, and to hopefully strip down the number of flags users need to provide when installing a profile in a gitops repo.

**Suggested UX/API change**
A new subcommand is added to `prepare` (is that verb sticking around?). Currently we have `pctl prepare` which puts CRDs etc on the cluster. We could have two new resource subcommands: `cluster` and `repo`, or smth. The idea is that users would/could run `prepare cluster` followed by `prepare repo`. Users can provide the information we can only get from them (interactively?), and we discover what we can without input. There should be sensible defaults.

**File location**
3 different locations for this have been suggested so far:
- "Global": A single file lives in the home dir (similar to kubeconf and other things). Repo/cluster details are saved under a "context" which users can provide during install. (Given they still need to physically be in the repo when they call a command, maybe this is just a recipe for disaster.... or maybe the configfile will get us away from that requirement 🤔 )
- "National": Users can configure multiple clusters from a single gitops repo (scoped in directories), it might make sense to commit the config file at the top level of the repo and have it contain the details of all clusters managed by that repo. The "context" thing would still apply but on a smaller scale. The above "Global" plan would also work for this too, it is just a matter of whether we think there is value in committing it there.
   ```
   ├── cluster-one
   │   ├── flux-system
   │   │   └── blah.yaml
   │   └── profile-crap
   │       └── thing.yaml
   ├── cluster-two
   │   ├── flux-system
   │   │   └── blah.yaml
   │   └── profile-crap
   │       └── thing.yaml
   └── .pctl
   ```
- "Local": The file is committed within the directory dedicated to the particular cluster. 
   ```

   ├── cluster-one
   │   ├── flux-system
   │   │   └── blah.yaml
   │   ├── .pctl
   │   └── profile-crap
   │       └── thing.yaml
   └── cluster-two
       ├── flux-system
       │   └── blah.yaml
       ├── .pctl
       └── profile-crap
           └── thing.yaml
   ```
-------------------------

These notes are just starting points, feel free to come up with whatever makes sense, or to scrap the whole idea if it does not seem like the right move.

**Goal**:
- We want to get the information pctl needs to operate
- ... in a way that is intuitive for users
- ... removing some of the burden of flags for pctl install

I believe there is a proposal template either in the pctl or the profiles repo. You can also find a guide in eksctl which would apply here: https://github.com/weaveworks/eksctl/blob/main/CONTRIBUTING.md#proposals

**Comment by Skarlso** [comment]
>"Global": A single file lives in the home dir (similar to kubeconf and other things). Repo/cluster details are saved under a "context" which users can provide during install. (Given they still need to physically be in the repo when they call a command, maybe this is just a recipe for disaster.... or maybe the configfile will get us away from that requirement 🤔 )

Potentially, yes. If they also define the repo root we could get that from the config instead. Fo pctl could be run anywhere.

**Comment by aclevername** [comment]
We should checkout how wego uses the `.wego` directory, there might be some norms to follow.

**Comment by Skarlso** [comment]
Looks like user's home `.wego`. But there are also appears to be some usage from the current running folder which is also `.wego`. But the main usage is `${HOME}/.wego`.

**Comment by aclevername** [comment]
> Looks like user's home `.wego`. But there are also appears to be some usage from the current running folder which is also `.wego`. But the main usage is `${HOME}/.wego`.

oh I thought the `.wego` was in the repository :thinking:

**Comment by Skarlso** [comment]
For example:

```go

func (f *FluxClient) fluxPath() (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", errors.Wrap(err, "failed getting user home directory")
	}
	path := fmt.Sprintf("%v/.wego/bin", homeDir)
	return fmt.Sprintf("%v/flux-%v", path, version.FluxVersion), nil
}

```

**Comment by aclevername** [comment]
## Spike outcome
[Spike code](https://github.com/weaveworks/pctl/tree/spike-config)
I went ahead with a spike where we introduce a `.pctl/` file *inside the git repository*. E.g:
```
├── cluster-one
│   ├── flux-system
│   │   └── blah.yaml
│   └── profile-crap
│       └── thing.yaml
├── cluster-two
│   ├── flux-system
│   │   └── blah.yaml
│   └── profile-crap
│       └── thing.yaml
└── .pctl
```

I added an extra step to the `pctl prepare` command, although as noted in the original issue this could be separated into `pctl prepare cluster` and `pctl prepare repo`. The command locates the top-level git directory by running `git rev-parse --show-toplevel` and creates the `.pctl/config` file containing the `git-repository` flag content. Each time a `pctl install` is run it looks up the `.pctl/config` file and reads the value. Example (run from inside a `foo/bar` directory in my git repository dir):

```
jake@jake-weave [15:36:44] [~/weave/gitops/foo/bar] [main *]
$ pctl prepare --git-repository foo/bar
Checking if flux namespace exists...done.
Checking for flux CRDs...done.
Waiting for resources to be ready...profiles-controller-manager: deployment ready
done.

jake@jake-weave [15:36:46] [~/weave/gitops/foo/bar] [main *]
-> % cat ../../.pctl/config
foo/bar

jake@jake-weave [15:36:50] [~/weave/gitops/foo/bar] [main *]
$ pctl install nginx-catalog/weaveworks-nginx
generating profile installation from source: catalog entry nginx-catalog/weaveworks-nginx/latest
installation completed successfully

jake@jake-weave [15:38:05] [~/weave/gitops/foo/bar] [main *]
$ cat weaveworks-nginx/weaveworks-nginx/artifacts/nested-profile/nginx-server/HelmRelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  creationTimestamp: null
  name: pctl-profile-bitnami-nginx-nginx-server
  namespace: default
spec:
  chart:
    spec:
      chart: weaveworks-nginx/artifacts/nested-profile/nginx-server/nginx/chart
      sourceRef:
        kind: GitRepository
        name: bar
        namespace: foo
  interval: 0s
status: {}

```
