### ISSUE TITLE
Spike: 3-way merge for upgrades

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#164]
**What feature/behavior/change do you want?**
I want to be able to upgrade a profile, but I also want to me able to make changes to the local profile after I've installed it. We need to add support for upgrading via a [3 way merge](https://en.wikipedia.org/wiki/Merge_(version_control)#Three-way_merge)
![image](https://user-images.githubusercontent.com/19669095/123088573-cd64af80-d41d-11eb-8fd3-8d2dd5464f01.png)

In the above image:
- C is the starting `pctl install weaveworks-nginx/v0.1.0` output
- A is the local changes a user has made after installing, e.g. such as changing the number of replicas from 2 to 3 in a `deployment.yaml` file
-  B is the `v0.1.1` release of the profile the author has released
-  D is where we want to get to, where we update the users local profile to `v0.1.1` while maintaining the users changes to `deployment.yaml` (assuming its unchanged in `v0.1.1`, otherwise merge conflict?)

Lets spike around with doing this and see how it works. Outcomes:
- Spike code
- Demo to the team to gain a shared understanding

thoughts:
- look at the kubectl example: https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/apply/patcher.go#L108
- how does this work when file names get changed? Does git provide some functionality we can re-use?

**Comment by Skarlso** [comment]
Note:

Unmarshalling these objects results in some unwanted empty fields which are not nil but empty maps so marshalling will not implicitly remove them. Surely there is something in Go already doing this, but alas, our search came back empty handed. We did write a little function which will remove empty fields ( after some searching ) which goes like this:

```go

func removeNulls(m map[string]interface{}) bool {
	changed := false
	val := reflect.ValueOf(m)
	for _, e := range val.MapKeys() {
		v := val.MapIndex(e)
		if v.IsNil() {
			delete(m, e.String())
			changed = true
			continue
		}
		if v.IsZero() {
			delete(m, e.String())
			changed = true
			continue
		}
		if i, ok := v.Interface().(map[string]interface{}); ok {
			if len(i) == 0 {
				delete(m, e.String())
				changed = true
				continue
			}
		}
		switch t := v.Interface().(type) {
		case map[string]interface{}:
			removeNulls(t)
		}
	}
	return changed
}

```

Note, you'll have to call this as many times as `changed`. We will however, go with the approach of not caring, and include empty fields in the output yaml which will look something like this:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
spec:
  paused: true
  replicas: 5
  selector: null
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers: null
status: {}
```

The local changes will contain this and if ever anyone complains, feel free to add the above function and "fix" the output.

**Comment by aclevername** [comment]
https://github.com/weaveworks/pctl/tree/spike-merge/spike
