### ISSUE TITLE
Upgrade proposal

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#194]
# `upgrade` command proposal

For details on the research around this, please see [spike](https://github.com/weaveworks/pctl/issues/164).

## Constraints

Upgrade only works for catalog installed profiles for which it's possible to determine upstream versions. Dev profiles, aka profiles installed via direct URL and branch, are not supported by `upgrade` yet. However, once versioning with commit hash, or something similar is introduced, they should also be upgradable.

## Using plain `git`

The git approach presents a simple way of merging things and users hopefully are already familiar with resolving Git based conflicts and merges because of flux and the GitOps nature of these tools.

This approach fits well within the current architecture because we already have a git package which takes care of dealing with everything that's git.

### Cons

- Git is really dumb and does a line-by-line comparison. Meaning it's not yaml structure aware and will not check integrity of said files
- Because of this, it won't be able to understand appends to lists properly and won't be able to handle things like, both local and upstream changed and added an item to a list
- Not yaml aware will merge whatever is there as it is line-by-line

### Pros

- Tracks changes in all files, not just Kubernetes objects -- opposed to the Kubernetes way, described later
- Familiarity
- Easy to implement
- There is already support for it
- Easy to display merge conflict errors to the end user
- Merge conflict error familiarity

## Using Kubernetes

There is another way of resolving / doing merges with Kubernetes objects and that is, using whatever `kubectl` does.
`kubectl` is using a combination of a three way merge and sending off a full patch to Kubernetes. The resulting patch
of the three way merge works really well for Kubernetes objects and results in nice merges when there are things like,
additions to lists. And it's yaml syntax aware so it will scream if the yaml is invalid after a merge.

However, Kubernetes merge is only aware of Kubernetes objects, so it would track changes in things like, local chart files
which aren't valid Kubernetes objects. Also, the diff is unexpected and not git standard and it's hard to reconcile / understand.

### Cons

- Only understand Kubernetes objects
- Conflict error output is hideous
- It adds complexity to the code. It will add even more dependency on Kubernetes libraries.
- No familiarity from majority of users, unless the user did a lot of patching using `kubectl`

### Pros

- Nice way of merging Kubernetes objects and is more clever than `git`
- Kubernetes is doing it, so it's tested and battle hardened strategy
- Yaml syntax awareness

## UX

The user is notified that there is a new version available when using `list`:

```bash
pctl list
NAMESPACE       NAME            SOURCE                                  AVAILABLE UPDATES
default         pctl-profile    nginx-catalog/weaveworks-nginx/v0.1.0   v0.1.1
```

Once a new version is available using `upgrade` downloads the new resources and does a merge with current changes.

The proposed command should look something like this:

```
pctl upgrade <path-to-profile> <version>
```

`profile-installation.yaml` file will contain the name of the profile.

Following the above list example this would look something like this:

```
pctl upgrade <path-to-installed-profile> v0.1.1
```

The following items should be possible while upgrading:

- output -- the location of the profile installation directory. 
- overwrite -- just take whatever changes there are upstream and overwrite the local ones completely
- when switching major versions -- display a warning and possible a `y/n` that it could be a breaking change
- create-pr -- same like install, optionally create a pr out of the changes

**Comment by Skarlso** [comment]
The issue presented here can better be collaborated on in this document:
https://docs.google.com/document/d/1rhtmdzI1SHXKLM2Ys4WC-ljIY60dF-9b61RT5P92990/edit?usp=sharing

**Comment by Skarlso** [comment]
_Note_: The chosen way forward is the Git approach.

**Comment by Skarlso** [comment]
* Updated with new changes from the doc.

**Comment by nikimanoledaki** [comment]
This issue will collect other `upgrade`-related stories.
