### ISSUE TITLE
pctl version

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#196]
Is not a thing yet:

```bash
$ pctl --version
Incorrect Usage. flag provided but not defined: -version

$ pctl version
No help topic for 'version'
```

😭

**Comment by Skarlso** [comment]
Hah, I did say that at some point. :D What's the way we want to do this? Shall we use build flags? 

```Makefile
VERSION ?= v0.0.1

# List the GOOS and GOARCH to build
GO_LDFLAGS_STATIC="-s -w $(CTIMEVAR) -extldflags -static -X 'main.version=${VERSION}'"
```

And then in the code we can have a var in main 

```go
var (
	version = "v0.0.0-dev"
)
```

Which is then overwritten on build time so the binary will have the right value. BTW, [goreleaser](https://goreleaser.com/customization/build/#passing-environment-variables-to-ldflags) can also set version var. 

```
builds:
  - ldflags:
   - -s -w -X "main.goversion={{.Env.GOVERSION}}"
```

and then

```
GOVERSION=$(go version) goreleaser
```

**Comment by Skarlso** [comment]
Which I'm sure is already a known thing. :D I'm just excited. :D

**Comment by nikimanoledaki** [comment]
Some UX considerations to keep in mind esp with wego (see tag option above)
