### ISSUE TITLE
Create an upgrade command using `git`

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#206]
Following the discussion in [Upgrade Proposal](https://github.com/weaveworks/pctl/issues/194) we would use Git initially to merge changes.

# Introduce an `upgrade` command

This command should use `git` in the background. Note that we already have a Git library, so this should be an addition to that interface. Call it something sensible like `Merge` or `Diff`.

# Do the merge

- get the base version and put the generated artifacts into a temp git repo
- get the user's artifacts and put them into a branch
- get the updates and merge them into main
- merge main into user's changes
- copy out the changes
- if there was an error because of a conflict, show that conflict to the user (probably just `git status` output)
- in either case, the result should be in the files so the user can reconcile them

# Example

Gather versions first:

```
pctl list
NAMESPACE       NAME            SOURCE                                  AVAILABLE UPDATES
default         pctl-profile    nginx-catalog/weaveworks-nginx/v0.1.0   v0.1.1
```

than update:
```
pctl upgrade ./my-profile v0.1.1
Upgrading <profile-name> to v0.1.1 from v0.1.0... done.
```

in case of a conflict.

```
pctl upgrade ./my-profile v0.1.1
Upgrading <profile-name> to v0.1.1 from v0.1.0... conflict.
Please inspect the generated content for more details.
```

in case of an error.

```
pctl upgrade ./my-profile v0.1.1
Upgrading <profile-name> to v0.1.1 from v0.1.0... error.
Further error details...
```

**Comment by aclevername** [comment]
@Skarlso can you add some example commands and output?

**Comment by Skarlso** [comment]
Yeah, sure.

**Comment by Skarlso** [comment]
@aclevername do these make sense?

**Comment by aclevername** [comment]
spike code: https://github.com/weaveworks/pctl/issues/164

**Comment by aclevername** [comment]
Closed by https://github.com/weaveworks/pctl/pull/221
