### ISSUE TITLE
Do not return empty summary when profile does not exist

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#21]
Right now when I attempt to `show` a profile that does not exist I get this:

```sh
$ ./pctl --catalog-url http://localhost:8000 show weaveworks-nginx/nginx
retrieving information for profile weaveworks-nginx/nginx:

name: ""
description: ""
version: ""
catalog: ""
url: ""
maintainer: ""
prerequisites: []

```

In this case neither the catalog source, nor the profile exists. We should have it so that if either one does not exist, we return a sensible message, rather than empty strings.

**Comment by cPu1** [comment]
This is already addressed in https://github.com/weaveworks/pctl/pull/17. When a profile doesn't exist, an error is returned `fmt.Errorf("unable to find profile `%s` in catalog `%s`", profileName, catalogName)`

I'll add another test to ensure the error message is correct.

**Comment by Callisto13** [comment]
Amazing, thanks!
