### ISSUE TITLE
Some of the names that we generate for pctl artifacts are getting too long

### ISSUE THREAD

**Issue by Skarlso** [weaveworks/pctl#212]
```
pctl-profile-depends-on-nginx-depend-on-this-redis-master-85744d7479
```

Is longer than the allowed 63 characters.

```
-master-85744d7479
```

Is added by redis, but the rest is us.

### Labels
Lets shorten the name to `<profile-installation-name>-<sha>` (look at how pods get a sha added at the end) and set labels with the fully descriptive names. Labels for each component of the name, e.g.:
- profile name
- branch name/tag
- artifact name
- nested profile

### installation.yaml
Keep our current naming, save it in installation.yaml, read it back when needed

### Make it shorter
Come up with a naming schema which is shorter while staying unique and useful

**Comment by cPu1** [comment]
Explore saving generated reference in profile installation file.

**Comment by aclevername** [comment]
I put togethere a little Miro board to expand upon what the current artifact names look like

https://miro.com/app/board/o9J_l3eeBso=/
![Profile Artifacts - Frame 1](https://user-images.githubusercontent.com/19669095/128853741-016cac66-f1ba-4129-81a8-1fe458c34767.jpg)
