### ISSUE TITLE
Automate and tag releases

### ISSUE THREAD

**Issue by Himangini** [weaveworks/pctl#233]
**What feature/behavior/change do you want?**
At the moment currently release process involves manually created tag and pushing it, it will be nice if we automate this process that can be used by the version flag to show pctl version. example workflow [here ](https://github.com/weaveworks/eksctl/blob/main/.github/workflows/tag-release.yaml)

**Why do you want this feature?**
Makes our life easier 🤷🏻‍♀️

**Comment by aclevername** [comment]
https://github.com/weaveworks/pctl/pull/267
