### ISSUE TITLE
installing a profile with a kustomize artifact from top-level repository doesn't work 

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#237]
**What were you trying to accomplish?**
`pctl install` https://github.com/chanwit/mlops-profile/tree/0c45e5e99dd273a993e18a00e703283ec4199eaf using the `--profile-path/branch/url` flags

**What happened?**
It fails to copy the kustomize artifacts. `failed to move folder: lstat /tmp/cloned_profile419553062957918/mlops/kfp-cluster-scoped: no such file or directory`. 
It should attempt to copy

-  `/tmp/cloned_profile419553062957918/kfp-cluster-scoped`

but instead it attempts
-  `/tmp/cloned_profile419553062957918/mlops/kfp-cluster-scoped`. 

This is probably a bug to how we handle top-level profiles, looks like the profile name is getting appended into the path when it shouldn't

**How to reproduce it?**
pctl install the above url

**Logs**

**Anything else we need to know?**

**Versions**

**Comment by Skarlso** [comment]
I have a solution for this, but I won't do it, until #235 is done, because it touches the builders and how we define SpraseFolder.

**Comment by Skarlso** [comment]
This has been implicitly fixed by #235
