### ISSUE TITLE
Refactor `pctl prepare` to `pctl install`

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#242]
**What feature/behavior/change do you want?**
Makes more sense now that we have `pctl add` and is consistent with wego/flux

**Comment by nikimanoledaki** [comment]
`pctl prepare` (or future `pctl install`) has the following output:
```
Waiting for resources to be ready...profiles-controller-manager: deployment readydone.
```
Let's make sure it also matches the output of flux :)
