### ISSUE TITLE
pctl add's flag to specify target-namespace of the resources

### ISSUE THREAD

**Issue by chanwit** [weaveworks/pctl#243]
Background:

My MLOps profile contains a Namespace manifest for creating "kubeflow" namespace and all resources in the profile must be installed into the "kubeflow" namespace only. 

Currently the "pctl add" command assume that the namespace is "default" and it affects both kustomization and the target namespace of the profile. 

I didn't want my profile to install all resources into the "default" namespace. So I ran "pctl add --namespace=kubeflow ...".

The result was:
1. ProfileInstallation had namespace=kubeflow
2. Kustomize objects had namespace=kubeflow
3. Kustomize objects had targetNamespace=kubeflow

and this caused a problem because there was no "kubeflow" ns prior to the installation of this profile (kubeflow ns would be created by a manifest of the profile)

What I'd like to see is that.
I could be able to issue:
"pctl add --namespace=profiles-system --target-namespace=kubeflow ...".

then

1. ProfileInstallation has namespace=profiles-system
2. Kustomize objects have namespace=profiles-system
3. Kustomize objects have targetNamespace=kubeflow

**Comment by aclevername** [comment]
Thanks for opening the issue @chanwit!  

Do you specifically want to be able to create the installation/kustomize objects in a different namespace to the targetNamespace, or is that just a suggested way for getting around the namespace not existing when the installation is getting applied?

We could change it so pctl creates the namespace first, and then applies the rest of the installation afterwards to get round the error.

**Comment by chanwit** [comment]
In many cases, there's a chance that a Profile is responsible for creating its own namespace, like this: https://github.com/chanwit/mlops-profile/blob/main/kfp-cluster-scoped/kfp_cluster_scoped.yaml#L4

After lot of thoughts,  I think we should address the former by allowing users to specify the target namespace.
(My first idea of letting `pctl` to create a namespace as the workaroud would cause another problem)

**Comment by chanwit** [comment]
BTW, why are we forcing a Profile to install into a specific target namespace?

**Comment by chanwit** [comment]
and what if a profile contains resources for different namespaces? 
For example the complete Kubeflow setup contains resources for both `istio-system` and `kubeflow`. Would this target namespace accidentally change semantics of resources in the profile?

**Comment by aclevername** [comment]
> BTW, why are we forcing a Profile to install into a specific target namespace in the first place?

I think we had always just thought of a profile going into a single namespace, this is an interesting point raised. 



> and what if a profile contains resources for different namespaces?
> For example the complete Kubeflow setup contains resources for both `istio-system` and `kubeflow`. Would this target namespace accidentally change semantics of resources in the profile?

How does that work when your deploying it via kustomization? Do you just not set the `targetNamespace` and it deploys the resources in the namespace they are already targetting?

**Comment by chanwit** [comment]
In case of the full Kubeflow setup, I just don't set the target namespace.

Maybe if user not specify --target-namespace, the CLI could just check if it's null and skip generation of the targetNamespace field. wdyt?

**Comment by aclevername** [comment]
> In case of the full Kubeflow setup, I just don't set the target namespace.
> 
> Maybe if user not specify --target-namespace, the CLI could just check if it's null and skip generation of the targetNamespace field. wdyt?

I think that makes a sense. Although the more flags the more confusion we will cause :sweat_smile:. Do we think the pctl user installing the profile would be the one who wanted to configure this, or should it be up the profile author? Perhaps a new field in the artifacts array for specifying target-namespace (or turning it off completely).

@bigkevmcd curious for your thoughts on this.

**Comment by bigkevmcd** [comment]
> > In case of the full Kubeflow setup, I just don't set the target namespace.
> > Maybe if user not specify --target-namespace, the CLI could just check if it's null and skip generation of the targetNamespace field. wdyt?
> 
> I think that makes a sense. Although the more flags the more confusion we will cause 😅. Do we think the pctl user installing the profile would be the one who wanted to configure this, or should it be up the profile author? Perhaps a new field in the artifacts array for specifying target-namespace (or turning it off completely).

Something to think about, what if you want to install the same profile multiple times?

You would probably want to specify different namespaces, but maybe not always?

**Comment by Skarlso** [comment]
We should discuss this issue on planning.

**Comment by Skarlso** [comment]
We decided not to take this on, because usually if a Helm chart comes with a namespace that's a known namespace and has a reason for it. But if not, you can change it with values in the chart it self? Also, that we shouldn't install Profiles multiple times.
