### ISSUE TITLE
Add flux-like tickmarks and output to all output

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#245]
We should make sure we match the UX style of flux in the output of all commands, for example:
- tickmarks e.g. ✔, ►, etc. ✨
- style for wording
- style for error messages

`pctl add` and `pctl install` in particular should be adjusted (other commands provide a standard `get` output)

From flux:
https://github.com/fluxcd/flux2/blob/4f4f0d70a41e56d8b11e5f4ec1dcd2ae76d89c7f/cmd/flux/log.go#L28-L50

**Comment by nikimanoledaki** [comment]
@aclevername did we want to add a flag or something that gives an alternative to tickmarks, to make the output machine-readable? I can't find if or how flux does this..

**Comment by Skarlso** [comment]
Flux doesn't provide you with an option like that. We thought it would be nice to add because pctl already has something like `--fromat=json`. Which wouldn't really fit with emojis.
