### ISSUE TITLE
Rename `--profile-url` to `--profile-repo-url `

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#246]
**What feature/behavior/change do you want?**

It would be nice if we could rename `--profile-url` to `--profile-repo-url `. 

**Why do you want this feature?**

The wording of `--profile-url` is a bit misleading: intuitively, it seems to refer to the full URL to the profile e.g. `https://github.com/nikimanoledaki/demo-profile/blob/main/profile.yaml`, but it actually refers to the repo containing the profile, e.g. `https://github.com/nikimanoledaki/demo-profile`

**Comment by aclevername** [comment]
update excel spreadsheet with commands
