### ISSUE TITLE
Rename `$GIT_TOKEN` to match flux's `$GITHUB_TOKEN`

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#247]
**What feature/behavior/change do you want?**

This is a bit nit but it would be nice to rename `$GIT_TOKEN` to match flux's `$GITHUB_TOKEN` if possible.

**Why do you want this feature?**

I got this error:
```
pctl add \
  --profile-url https://www.github.com/nikimanoledaki/demo-profile \
  --create-pr \
  --pr-repo nikimanoledaki/demo-profile \
 --config-map configmap.yaml
generating profile installation from source: repository https://www.github.com/nikimanoledaki/demo-profile, path: . and branch main
installation completed successfully
Creating a PR to repo nikimanoledaki/demo-profile with base main and branch pctl-profile-4d1752
failed to create scm client: failed to create scm client: No Git OAuth token specified for $GIT_TOKEN
```

I set it to `$GITHUB_TOKEN`, which I had set as part of my [flux config](https://fluxcd.io/docs/get-started/#prerequisites). If we could rename this to match the flux env var it will be one less step when using `pctl`! :) 

## Implementation
We need to change how we build the client to not use the environment, as the library uses `GIT_TOKEN`
https://github.com/weaveworks/pctl/blob/31164f3f2c9fe6271ba07f2c0347f2f5ff33d21c/pkg/git/scm_git.go#L31-L42

**Comment by Skarlso** [comment]
There was a reason why it's GIT_TOKEN.... I just don't remember what. :D I'll check this out. :)

**Comment by Skarlso** [comment]
What about Gitea? Or any private servers then? I think GIT_TOKEN is fine to be honest.

**Comment by nikimanoledaki** [comment]
Yeah, those are valid points. I think Flux has something for private servers too. I raised this more so that we can discuss maintaining consistency with Flux and Wego regarding this!

**Comment by aclevername** [comment]
integration tests need to change from using `GIT_TOKEN` (currently if its not set, it skips certain tests)
