### ISSUE TITLE
Add ability to edit commit message along with `--create-pr`

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#252]
**What feature/behavior/change do you want?**

When I use `--create-pr`, I would like to be able to set the commit message. Currently, it defaults to `Push changes to remote`. `pctl add --create-pr -m "my-message"` (or `--message`)

**Why do you want this feature?**

The default commit message doesn't tell me much.

**Comment by aclevername** [comment]
update excel spreadsheet with commands

**Comment by Skarlso** [comment]
@aclevername Link to the spreadsheet?
