### ISSUE TITLE
`--version` prints older version

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#254]
**What were you trying to accomplish?**

I downloaded the latest binary for pctl, `2.0`, and tried to print the version with `pctl --version`. I expected the output to show `2.0` but it was `1.0`. 

**What happened?**

```
➜  ~ pctl --version
pctl version 0.1.0-dev+6b75a51.2021-07-28T13:14:29Z
```

related to #241 and #240 

**How to reproduce it?**

**Logs**

**Anything else we need to know?**

**Versions**

**Comment by aclevername** [comment]
fixed in https://github.com/weaveworks/pctl/issues/240
