### ISSUE TITLE
Rename `--git-repository` because it's too generic

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#256]
**What feature/behavior/change do you want?**

Let's rename the `--git-repository` flag to specify which Git Repository resource we are referring to. 

In this case, this flag is referring to the path of the `GitRepository` resource that is used by Flux and lives in the cluster. The value we set it to must be in the format `<flux-namespace>/<GitRepository resource>` e.g. `--git-repository flux-system/flux-system`

**Why do you want this feature?**

`--git-repository` as a flag is a bit generic and doesn't intuitively indicate which repo or resource it's referring to, particularly in the context of `--profile-repo-url` and `--pr-repo`.

**Suggestions**
- `--git-repository-resource`
- `--flux-git-repository`

**Flux reference**
For reference, the flux CLI wording for this resource is as follows:
```
 # List GitRepository sources and their status
 flux get sources git

 # Trigger a GitRepository source reconciliation
 flux reconcile source git flux-system

 # Export GitRepository sources in YAML format
 flux export source git --all > sources.yaml
```

**Comment by Skarlso** [comment]
Agreed. The name is not concrete enough to know what git-repository is.

**Comment by Skarlso** [comment]
I think this can be closed now that we reformed how this stuff works.
