### ISSUE TITLE
[nice to have] Add `pctl add catalog`

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#257]
**What feature/behavior/change do you want?**

It would be nice (but maybe premature/unnecessary right now) to have a `pctl add catalog` command that generates the catalog YAML, such as `pctl add catalog --name x --url y --namespace z`

**Why do you want this feature?**

So that the YAML is generated for me (even though it's 7 lines) :D

**Comment by Himangini** [comment]
Closing this off since we no longer need this.
