### ISSUE TITLE
`pctl get --catalog` is not listing dynamically-created catalog's profiles

### ISSUE THREAD

**Issue by nikimanoledaki** [weaveworks/pctl#258]
**What were you trying to accomplish?**

I was trying to replace my manually-created catalog with a dynamically-created catalog and then list my new profiles with `pctl get --catalog`.

**What happened?**

This failed and I still see the old catalog's profiles, as shown below.

**How to reproduce it?**

1. Follow the [steps](https://profiles.dev/docs/catalog-docs/add-profiles#create-a-manual-catalog-source) in the docs for creating a manually-created catalog and `kubectl` apply it. 
2. `pctl get --catalog` should show the following output: 
```
$ pctl get --catalog
CATALOG/PROFILE         VERSION DESCRIPTION
nginx-catalog/nginx     v1.0.0  This installs some nginx.
```
3. Then, follow the [steps](https://profiles.dev/docs/catalog-docs/add-profiles#dynamically-populate-a-catalog) to create a dynamically-created catalog. 
4. Doing `pctl get --catalog` does not list the new catalog's profiles. It still shows the manually-created catalog's profiles.

However, the `profilecatalogsources` looks like it has passed, even though the `get` is not working:
```
$ k get profilecatalogsources.weave.works -o yaml
apiVersion: v1
items:
- apiVersion: weave.works/v1alpha1
  kind: ProfileCatalogSource
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"weave.works/v1alpha1","kind":"ProfileCatalogSource","metadata":{"annotations":{},"name":"nginx-catalog","namespace":"default"},"spec":{"repositories":[{"url":"https://github.com/weaveworks/profiles-examples"}]}}
    creationTimestamp: "2021-08-03T13:19:55Z"
    generation: 3
    name: nginx-catalog
    namespace: default
    resourceVersion: "282530"
    uid: bd8fc57c-1de8-4e19-9b72-53c21559340f
  spec:
    repositories:
    - url: https://github.com/weaveworks/profiles-examples
  status:
    scannedRepositories:
    - tags:
      - bitnami-nginx/v0.0.1
      - nested-nginx/v0.0.1
      - weaveworks-nginx/v0.1.1
      - weaveworks-nginx/v0.1.0
      - bitnami-nginx/v0.0.2
      - nested-nginx-2/v0.0.1
      - nested-nginx-1/v0.0.1
      url: https://github.com/weaveworks/profiles-examples
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Logs**

**Anything else we need to know?**

**Versions**

**Comment by aclevername** [comment]
PR: https://github.com/weaveworks/profiles/pull/295
