### ISSUE TITLE
Support for GKE (and others cloud providers) when `pctl install`ing 

### ISSUE THREAD

**Issue by foot** [weaveworks/pctl#274]
At the moment `pctl install` doesn't seem to work with GKE as client-go is missing the auth module.

```
$ pctl install
failed to build kubernetes client: failed to create client: no Auth Provider found for name "gcp"
```

From: https://krew.sigs.k8s.io/docs/developer-guide/develop/best-practices/ 

> Import authentication plugins (Go)
> By default, plugins that use client-go cannot authenticate to Kubernetes clusters on many cloud providers. To address this, include the following import in your plugin:
> `import _ "k8s.io/client-go/plugin/pkg/client/auth"`

**Comment by aclevername** [comment]
thanks for raising this @foot ! Can we pair at some body to test the fix works? I don't have access to a GKE cluster myself :smile:
