### ISSUE TITLE
`pctl add` commits all unstaged files in working directory

### ISSUE THREAD

**Issue by foot** [weaveworks/pctl#277]
**What were you trying to accomplish?**

`pctl add` to create a PR to add a profile to the cluster.

**What happened?**

PR was created as expected! However it contained all the uncommited/unstaged stuff in the working directory too, some logs / tarballs and random things. I'm not very tidy sometimes.

**How to reproduce it?**

1. Follow tutorial https://profiles.dev/docs/tutorial-basics/install-a-profile
2. `touch foo.txt`
3. `pctl add --create-pr ...`
4. Check PR and expect `foo.txt` to not be included in it.

**logs**

```
GIT_TOKEN=$GITHUB_TOKEN pctl add --profile-repo-url git@github.com:org/repo --profile-path management/profile-tests/repo --create-pr --pr-repo org/repo --pr-branch add-simple-profile
generating profile installation from source: repository git@github.com:org/repo, path: management/profile-tests/repo and branch main
installation completed successfully
Creating a PR to repo org/user with base main and branch add-simple-profile
using driver: github and serverURL:
creating new branch
adding unstaged changes
pushing to remote
Creating pull request with :  org/repo main add-simple-profile
PR created with number: 189 and URL: https://github.com/org/repo/pull/189
```

**Versions**

```
$ pctl --version
pctl version 0.5.0
```

**Comment by Callisto13** [comment]
Note for team: explore how WeGo handles various git edgecases
