### ISSUE TITLE
Return nice error if cluster without catalog API is targeted

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#29]
We currently instruct users to ensure their context is set to the correct cluster in order for the Proxy to pick up the catalog API.

pctl should return a helpful error in the case that the cluster they are directed at does not have a catalog API. (something which suggests either targeting the correct cluster or running our bootstrap command? 🤷‍♀️ )

**Comment by Skarlso** [comment]
right now if the cluster api can't be found it just errors with not found or nothing is there or it just simply isn't working. Do we want something else to happen if it can't locate catalog api?
