### ISSUE TITLE
Failed to create PR on a forked GitOps repo.

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/pctl#292]
**What were you trying to accomplish?**
Add the nginx profile to a wego repo.

**What happened?**
Failed to create the PR on the repo.

**How to reproduce it?**
1. create a kind cluster
2. run `wego gitops install`
3. run `wego app add .` to my fork of the podinfo-deploy repo (I believe this is there the problem is as we had the same problem on wego)
4. run 
```
pctl add \                                                                          
 --profile-repo-url https://github.com/weaveworks/nginx-profile \
 --profile-path . \
 --create-pr \
 --pr-repo https://github.com/myorg/podinfo-deploy \
 --pr-branch add-nginx-profile \
 --name sample-nginx-profile
```

**Logs**
Output from the call: 
```
► generating profile installation from source: repository https://github.com/weaveworks/nginx-profile, path: . and branch main
✔ installation completed successfully
► creating a PR to repo https://github.com/myorg/podinfo-deploy with base main and branch add-nginx-profile
► creating new branch

► adding unstaged changes

► pushing to remote

► Creating pull request with : https://github.com/palemtnrider/podinfo-deploymainadd-nginx-profile
✗ failed to create pull request: error while creating pr: Not Found
```
**Anything else we need to know?**

This repo is a fork from another repo.  I'm wondering if the PR was trying to create the PR using the upstream repo instead of my forked one.  We had this same error in Weave GitOps.

**Versions**
`pctl version 0.7.0`

**Comment by aclevername** [comment]
thanks for opening the issue @palemtnrider ! To be clear, your trying to make a PR into repo A from repo B (which is a fork of A)? If thats the case then yes I don't believe this will work, as we only support making PRs from within the same repo. I did look to see if we can easily change this, but looking at the underly `go-scm` package we use it doesn't appear to support specifying a fork when opening a pull request https://github.com/jenkins-x/go-scm/blob/ca0f320a99efb8436f8ba445c9558d32df71d1e8/scm/driver/github/pr.go#L69

This is less of a bug and more of a feature request, and a very reasonable one at that :smile: . @palemtnrider I will add it to discuss in this weeks planning

**Comment by Skarlso** [comment]
@aclevername Let's talk about this? :)
