### ISSUE TITLE
pctl get returns "No profiles found" when a catalog isn't defined

### ISSUE THREAD

**Issue by palemtnrider** [weaveworks/pctl#294]
**What were you trying to accomplish?**
List my current profiles

**What happened?**

I ran `pctl get` and it returned
```
INSTALLED PACKAGES
NAMESPACE       NAME                    SOURCE                                                  AVAILABLE UPDATES 
default         sample-nginx-profile    https://github.com/weaveworks/nginx-profile:main:.      -                

✗ No profiles found
```

The `No profiles found` was a bit confusing as it is really saying no catalogs available/configured.  If it printed the headers for the catalog listing it would be clearer.

**How to reproduce it?**

Use pctl to install a profile, sync it to the cluster, then run `pctl get` without configuring any catalogs.

**Logs**

**Anything else we need to know?**

**Versions**
0.7.0

**Comment by aclevername** [comment]
Thanks for opening the issue @palemtnrider !

> The No profiles found was a bit confusing as it is really saying no catalogs available/configured. If it printed the headers for the catalog listing it would be clearer.

So something like:
```
$ pctl get 
INSTALLED PACKAGES
NAMESPACE       NAME                    SOURCE                                                  AVAILABLE UPDATES 
default         sample-nginx-profile    https://github.com/weaveworks/nginx-profile:main:.      -                

PACKAGE CATALOG
CATALOG/PROFILE                 VERSION DESCRIPTION
-                               -
``` 

Or just the empty columns with the same error message? None of them look particularly clean IMO. Looking at what kubectl does:
```
k get pods
No resources found in default namespace.
```

if you get multiple types, which is similar to how we get installed and catalog profiles:
```
k -n flux-system get pvc,pods
NAME                                        READY   STATUS    RESTARTS   AGE
pod/helm-controller-69f8dd8887-6ggkv        1/1     Running   0          97m
pod/kustomize-controller-55d5f9ffdd-hlgqc   1/1     Running   0          97m
pod/source-controller-6bcfcd685d-9qb2n      1/1     Running   0          97m
```

Kubectl just silently ignores that it doesn't find any :thinking:

**Comment by Himangini** [comment]
I think we need to update this message to a meaningful message like `No Catalog profiles found` or something. The empty columns look more confusing
```
✗ No profiles found
```
