### ISSUE TITLE
Use `pctl` as a dependency of another cli tool

### ISSUE THREAD

**Issue by foot** [weaveworks/pctl#307]
**What feature/behavior/change do you want?**

We'd like to perform certain `pctl` tasks from another cli tool (`wego`). In this case we want to `pctl add` as part of another `upgrade` command.

The options seem to be:
1. require the user have the correct version of `pctl` installed in their `PATH` (a bit awkward)
2. bundle the `pctl` bin at the desired version within the `wego` binary as it currently [does with flux](https://github.com/weaveworks/weave-gitops/blob/9cc7812d1eb826a9c641b7f93322988c11f6a5a7/pkg/flux/setup.go#L12)
3. Change some of top level functions like `addProfile` to `AddProfile` so they can imported and used as go modules

Option 3 seems like the "easiest", but longer term cons include:
- With a go module we have to be more careful not to “refactor” away the exported functions
- ?

**Comment by Skarlso** [comment]
@aclevername Okay with going with `3.` ?

**Comment by aclevername** [comment]
> @aclevername Okay with going with `3.` ?

Obviously there is a cost to it but it seems reasonable.

@foot whats the cost of `1.` or `2.`? How have you found that with the flux binary so far?

**Comment by foot** [comment]
1. is a bit of a pain for user so would avoid
2. Feels okay too, bit of work around build tooling but the pattern is there already

@Himangini pointed out there are some other discussions around project integration which leans more towards option 2. So perhaps we see how that pans out.

We can do some initial work with option 1 for now while we explore a bit.

**Comment by foot** [comment]
Thanks for the discussion! Closing for now.
