### ISSUE TITLE
As a User I want to be able to be able to configure the default location my Profile installations go into

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#309]
Currently running `pctl add --name foo my-catalog/weaveworks-nginx` results in an `weaveworks-nginx` directory getting created in the same directory you ran the command in. Users can configure a different location by specifying the output directory, e.g. `pctl add --name foo -o put/it/here/ my-catalog/weaveworks-nginx`. 

Some users might always want the profiles to go into the same directory, e.g. `.wego/profiles/`. Lets add support for specifying a default installation directory, removing the need for the users to repeatedly specify it.

## Implementation
We already have a `.pctl/config.yaml` file that holds the GitRepository resource name/namespace for your Flux repository. This is created during the `pctl bootstrap` command. Lets add an additional flag `pctl bootstrap --default-dir` for specifying the default directory profile installations should go into. Now whenever a user runs `pctl add` and doesn't specify an output directory we will check the `.pctl/config.yaml` to see if this `default-dir` is set. If it is we use that directory as the output.

## Acceptance
1. cd into my Flux repository
2. run `pctl bootstrap --git-repostory foo/bar --default-dir .wego/profiles`
3. run `pctl add --name nginx my-catalog/weaveworks-nginx`
4. see that the `weaveworks-nginx` profile installation is at `.wego/profiles/weaveworks-nginx`. 
5. ???
6. profit

**Comment by Skarlso** [comment]
Aaaand we're back to `--out`, right? :D

**Comment by aclevername** [comment]
> Aaaand we're back to `--out`, right? :D

What do you mean :thinking: ? `--out` is a flag we support already

**Comment by Skarlso** [comment]
ah, so want a flag to save what `--out` will use permanently?

**Comment by aclevername** [comment]
> ah, so want a flag to save what `--out` will use permanently?

basically yeah! So people can enforce a particular directory structure
