### ISSUE TITLE
Pctl rebranding

### ISSUE THREAD

**Issue by Himangini** [weaveworks/pctl#318]
Based on the decision [here ](https://docs.google.com/document/d/1-QFqmiXg1njjRMMuP-Y6zuIUaEhePAb_o7SnIjxB1b4)

- [ ] Rename the Github repository `pctl` → `github.com/weaveworks/kivo-cli`
- [ ] Rename `pctl` to `kivo` and change references in the code base

**Comment by aclevername** [comment]
you miss-spelled `plux`!

**Comment by Himangini** [comment]
Cool to have a Logo for kivo

**Comment by Himangini** [comment]
We don't plan currently to release profiles as a standalone component. This is no longer required.
