### ISSUE TITLE
As a Profile Installer I don't have to get deploy key access to install a Profile from a private catalog

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#320]
**What feature/behavior/change do you want?**
As a Profile Installer I don't have to get SSH key access to install a Profile from a private catalog. Currently today if I run:
`pctl add weaveworks-catalog/weaveworks-private-profile` I must have in my ssh keychain locally:

- A key to clone the git repository that the `weaveworks-private-profile` lives in
- A key for any nested profiles that are contained inside the `weaveworks-private-profile`.

This is annoying. I would rather that `pctl add` *auto-magically* worked without me having to go fetch these keys manually.

## How private profiles work in catalogs work today
Before thinking about how to solve this problem, its worth mentioning how the catalog API works in relation to private profiles. A user can currently create a catalog that scans private repositories https://profiles.dev/docs/catalog-docs/add-profiles#adding-profiles-from-private-repositories, example:

```yaml
apiVersion: weave.works/v1alpha1
kind: ProfileCatalogSource
metadata:
  name: private-catalog
spec:
  repositories:
    - url: https://github.com/weaveworks/profiles-examples-private
      secretRef:
        name: profiles-examples-private-deploy-key # kubernetes Secret containing the ssh key
```

This means that the **Catalog API already knows where to get the SSH keys for gaining access to the private repository, and that the secret exists in the cluster**.

## Proposals
This outlines a couple of *possible* solutions, this isn't a fixed list :smile: feel free to comment with additions/suggestions.

### pctl fetches the secret from the cluster
As described above, the ssh key for gaining access to the private repository already exists in the cluster. We could add a new endpoint to the catalog API that either:
- Returned the private key
- Returned the name&namespace of the Secret containing the private key

The 1st option means we are transmitting the private key over the API, which might be a security concern. The 2nd option means the user (or auto-matically in pctl) can query kubernetes to get the Secret. This essentially just shifts some of the responsiblity out of the API, but means *the user has to have access to the kubernetes API when installing a profile*.

### pctl fetches the repositories from the cluster instead of cloning them locally
As described in https://github.com/weaveworks/profiles/issues/316 we could move the cloning of the private repositories into the cluster. When a user is running `pctl add` and the code needs to gain access to `github.com/foo/bar`, it could query the Catalog API to return a URL for downloading a tarball containing the git repository content. The simplest way to do this from the Catalog API is to create a `GitRepository` object per profile version. This might be costly, as we might need *a lot of GitRepository objects*. The API could generate them ad-hoc, and then cleanup after some reasonable time period. But this would introduce a lot of extra time into the `pctl add` flow, as the GitRepository resource might takes minutes to create a tarball.

### catalog server provides a private clone api

The catalog server would provide an API in these cases to use clone with the necessary credentials. It then could stream back the result through the API requiring little memory resources. The key here is streaming the result back and not cloning everything into memory and THEN transfer back the results. That would incur RAM costs for the catalog server.

This way, `kivo` doesn't need anything, just provide what it wants and then call clone. The downside is that it either needs a way to detect when something is private ( for example trying a clone, fails with auth error, fall back to catalog clone ) or, the user needs to signal that it's trying to clone a private repository with something like `--private`. This, however, would mean that it would use catalog clone for public repos a well, which isn't a problem per-say, just an observation.

### Other ideas
Feel free to add!

**Comment by aclevername** [comment]
@Himangini am I good to drag into planning for next week?

**Comment by Himangini** [comment]
> @Himangini am I good to drag into planning for next week?

No. Leave it under New, please. We've got Profiles Integration to focus on next week.

**Comment by Skarlso** [comment]
What if we just set up the catalog manager as a git proxy to github? That could then handle authentication, wouldn't have to store anything and would use local keys to ssh clone. Would only result in transfer costs.

**Comment by Skarlso** [comment]
Expanding on this, basically, kivo wouldn't call git clone in these cases, but catalog clone. And catalog clone would stream back the result to kivo.

**Comment by aclevername** [comment]
> Expanding on this, basically, kivo wouldn't call git clone in these cases, but catalog clone. And catalog clone would stream back the result to kivo.

feel free to update the original issue with this idea :smile:

**Comment by Skarlso** [comment]
Added. :)

**Comment by Himangini** [comment]
Given the new direction of profiles @aclevername @Skarlso do you think this is still needed? If so lets discuss in planning :)
