### ISSUE TITLE
Add support for pctl install via branch

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#55]
**What feature/behavior/change do you want?**
Currently `pctl install` only supports deploying via a catalog entry, e.g. `pctl install nginx-catalog/weaveworks-nginx/v0.1.0`. Lets add support for specifying a branch & URL manually. This lets users who are developing profiles use `pctl install` to test the logic.

`pctl install --branch master --url github.com/weaveworks/profiles-examples --path weaveworks-nginx`

**Why do you want this feature?**
To easily develop profiles

**Comment by aclevername** [comment]
need to think about what the new `pctl list` output shows when using branch & path @Skarlso

**Comment by Skarlso** [comment]
```
pctl list
NAME     NAMESPACE     SOURCE
                                           CATALOG                    PROFILE       VERSION
foo          default                nginx-catalog             weaveworks v0.1.0
foo          default                nginx-catalog             weaveworks v0.1.0
foo          default                nginx-catalog             weaveworks v0.1.0

                                 URL                                         BRANCH   PATH
testing  default       github.com/weaveworks/foo main          path/to/profile
```

**Comment by Skarlso** [comment]
Yeah, tablewriter is a pain in the arse. :/ So we settled on this:

```
./pctl list
NAMESPACE       NAME                    SOURCE
default         pctl-profile            nginx-catalog/weaveworks-nginx/v0.1.0
default         pctl-profile-branch     https://github.com/weaveworks/profiles-examples:branch-and-url:branch-nginx
```
