### ISSUE TITLE
Generated artifact files should not be 0755 

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#75]
Run `pctl install <foo>` then do `ls -l`. The generated files are all `0755`. We should be generating `0644`s.

**Comment by aclevername** [comment]
@Callisto13 correcting your titles for a change :grin:

**Comment by Callisto13** [comment]
The british spelling has an `e` 😏  so blame chrome spellcheck

**Comment by Callisto13** [comment]
Wont be at standup, but this is what I will be doing when I get back later.

Given in the code we are creating with `0777`, if i were to hazard a guess I would say that there is a `umask` of `0022` at play somewhere.
