### ISSUE TITLE
Review pctl CLI UX

### ISSUE THREAD

**Issue by Callisto13** [weaveworks/pctl#77]
Work with @bia and @davidstauffer to review the current UX and develop a set of patterns/guidelines/cohesive experience (similar to [this](https://docs.google.com/spreadsheets/d/1jcC_PheM6oEJGdKvkJu4Hp3bYMqeMUN7YhhNBGgcKfA/edit#gid=213375146)).

There is a lot of overlap here with other WeGo projects.

Targets:
- Commands and flags
- Stdout and Stderr messages

Outcomes should either be a PR (if alterations are very small), or a series of issues.

**Comment by aclevername** [comment]
https://github.com/weaveworks/pctl/issues/139
