### ISSUE TITLE
version should be optional in `pctl install`

### ISSUE THREAD

**Issue by aclevername** [weaveworks/pctl#79]
**What feature/behavior/change do you want?**
I want to be able to run `pctl install nginx-catalog/weaveworks-nginx` and have pctl detect the most up to date version

**Why do you want this feature?**
So that I don't have to worry about the version number

**Comment by Skarlso** [comment]
This is done now, isn't it? With the `latest` thing.

**Comment by Callisto13** [comment]
Done in https://github.com/weaveworks/pctl/pull/80
